# Generated by Django 3.1.2 on 2020-10-15 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='insdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
